"""PR creation via gh CLI."""

import subprocess
from pathlib import Path
from typing import Optional

from beehive.core.session import AgentSession


class PRCreator:
    """Handles PR creation via gh CLI."""

    def __init__(self, repo_path: Path):
        """Initialize with repository path."""
        self.repo_path = Path(repo_path)

    @staticmethod
    def check_gh_installed() -> bool:
        """Verify gh CLI is available."""
        try:
            subprocess.run(["gh", "--version"], capture_output=True, check=True)
            return True
        except (subprocess.CalledProcessError, FileNotFoundError):
            return False

    def create_pr(
        self,
        branch_name: str,
        base_branch: str = "main",
        title: Optional[str] = None,
        draft: bool = False,
        session: Optional[AgentSession] = None,
    ) -> str:
        """
        Create PR from branch.

        Steps:
        1. Push branch to remote
        2. Generate title if not provided
        3. Generate body with agent instructions and stats
        4. Create PR via gh CLI
        5. Return PR URL
        """
        # Push branch
        subprocess.run(
            [
                "git",
                "-C",
                str(self.repo_path),
                "push",
                "-u",
                "origin",
                branch_name,
            ],
            check=True,
        )

        # Generate title if needed
        if not title:
            title = self._generate_title(branch_name)

        # Generate body
        body = self._generate_body(branch_name, base_branch, session)

        # Create PR
        cmd = [
            "gh",
            "pr",
            "create",
            "--base",
            base_branch,
            "--head",
            branch_name,
            "--title",
            title,
            "--body",
            body,
        ]
        if draft:
            cmd.append("--draft")

        result = subprocess.run(
            cmd, capture_output=True, text=True, check=True, cwd=self.repo_path
        )
        pr_url = result.stdout.strip()
        return pr_url

    def _generate_title(self, branch_name: str) -> str:
        """Generate PR title from branch name."""
        # Extract name part: beehive/fix-auth-bug-a1b2c3d4 -> fix-auth-bug
        parts = branch_name.split("/")[-1].rsplit("-", 1)
        name = parts[0].replace("-", " ").title()
        return name

    def _generate_body(
        self,
        branch_name: str,
        base_branch: str,
        session: Optional[AgentSession],
    ) -> str:
        """Generate PR body with agent info."""
        body_parts = ["## Agent-Generated PR\n"]

        if session:
            body_parts.append(
                f"**Agent Instructions:**\n```\n{session.instructions}\n```\n"
            )
            body_parts.append(f"**Session ID:** `{session.session_id}`\n")
            body_parts.append(
                f"**Created:** {session.created_at.strftime('%Y-%m-%d %H:%M')}\n"
            )
            if session.preview_url:
                body_parts.append(
                    f"**Preview:** [{session.preview_url}]({session.preview_url})\n"
                )

        # Get diff stats
        try:
            result = subprocess.run(
                [
                    "git",
                    "diff",
                    "--stat",
                    f"{base_branch}...{branch_name}",
                ],
                capture_output=True,
                text=True,
                cwd=self.repo_path,
            )
            if result.stdout:
                body_parts.append(f"\n## Changes\n```\n{result.stdout}\n```")
        except subprocess.CalledProcessError:
            pass

        body_parts.append(
            "\n---\n*Generated by [Beehive](https://github.com/yourusername/beehive)*"
        )

        return "\n".join(body_parts)
